./sig.c: In function termsig_handler:
./sig.c:542:7: warning: possible asynchronous-unsafe function termsig_handler in signal handler termsig_sighandler [-fplugin=handler_plug.so]
       termsig_handler (sig);
       ^~~~~~~~~~~~~~~~~~~~~
./sig.c: In function set_signal_handler:
./sig.c:635:7: warning: possible asynchronous-unsafe function throw_to_top_level in signal handler sigint_sighandler [-fplugin=handler_plug.so]
       throw_to_top_level ();
       ^~~~~~~~~~~~~~~~~~~~~
